import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Main/Navbar/Navbar";
import Footer from "@/app/components/Main/Footer/Footer";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Land Treat",
  description: "Generated by create next app",
  keywords: ['property', 'real estate', 'land treat'],
        alternates: {
            canonical: `https://landtreat.com`,
        },
        other: {
            'geo.placename': 'India',
            'geo.country': 'in',
            'revisit-after': '7 days',
            'google-site-verification': 'jnaiHHuhKODc-lGAnJKwf2QOSutvBm5F6R-VVMfTaeU'
        },
        openGraph: {
            title: "Landtreat: Explore Property With Genuine Price",
            description: "Discover the best properties at authentic prices with Landtreat. Your trusted platform for transparent and genuine real estate deals, ensuring a seamless experience for property buyers and sellers.",
            url: `https://landtreat.com/`,
            type: 'website',
            siteName: 'Land Treat',
            images: [
              {
                url: `https://landtreat.com/og/og_image.png`,
                width: 1200,
                height: 630
              }
            ],
          },
          themeColor: '#2f69e6',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
