export const locationMappingData = {
    "Bhubaneswar": [
        "Acharya Vihar",
        "Aiginia",
        "Aiims",
        "airport",
        "Amanakuda Mouza",
        "Anda Bajpur",
        "Ashok Nagar",
        "Atala",
        "Badadhan pur",
        "Balianta",
        "Banqual",
        "Baramunda",
        "Begunia",
        "Bhanpur",
        "Bhimatangi",
        "Bhingarpur",
        "BHUBANESWAR PURI BYPASS",
        "Bomikhal",
        "bommasandra",
        "Botonda",
        "Chaitanya Prasad",
        "Chandaka",
        "Chandrasekharpur",
        "Chatabara",
        "Chatabara by pass road",
        "Chatrapur",
        "Cuttack to bhubaneswar",
        "Damana",
        "Daruthanga",
        "Dharitri vihar",
        "dhauli",
        "Dumduma",
        "Fire Station",
        "Fire Station Chhak",
        "Forest park",
        "Gadakana",
        "Gahira chhak",
        "Gangapada",
        "Ganjam",
        "GARAGE CHAKA",
        "Ghangapatana",
        "Godiapokhari",
        "Gohira chhaka",
        "Gothapatana",
        "Gothapatna",
        "Gudiapokhri",
        "gurudi jhatia",
        "hansapal",
        "Hansapala",
        "Hansapalo",
        "Hanspal",
        "Haripur",
        "info Valley",
        "Infocity",
        "Infovally",
        "Jagamara",
        "Janla",
        "Janla Infosys two",
        "Jasuapur",
        "Jatani gate",
        "Jatni",
        "JATNI MAIN GATE",
        "jay",
        "Jaydev Vihar",
        "Jharpada",
        "kaimatia",
        "Kalarahanga",
        "Kalinga Vihar",
        "kalpana squree",
        "kantabada",
        "Kapila Prasad",
        "Kashipur",
        "Kateni Square",
        "Kesura",
        "Khandagiri",
        "Khordha",
        "Khordha bologardha",
        "KHORDHA NH",
        "Khurda",
        "Koel Nagar Rourkela",
        "Kordha",
        "Kujimahal",
        "kuranga sasan",
        "laxmisagar",
        "Lingaraj",
        "Lingipur",
        "madanpur",
        "Mahalaxmipur, Khuntuni",
        "Malipada",
        "Mancheswar",
        "Mancheswar Railway Station, near Rajdhani Engineering College",
        "Master Canteen",
        "Nakhara",
        "Nandankanan",
        "Nayapali",
        "New Railway Station",
        "niladri Vihar",
        "Nuagaon",
        "Old Town",
        "Padasahi",
        "Pagala",
        "pahal",
        "Pahala",
        "palashuni",
        "palasuni",
        "Palasuni,near reliencefress ",
        "Panchagaon",
        "Panchgaon",
        "Patharagadia",
        "Patia",
        "Patia, Raghunathpur",
        "Patia,kalarahanga",
        "Patia,Padasahi",
        "Patrapada",
        "PHULANAKHARA",
        "Pitapali",
        "Pittapali",
        "Podapada",
        "pokhariput",
        "PURI CUTTACK NH",
        "Raghunathpur",
        "Ranga Bazar",
        "rangabazar",
        "Rasulgarh",
        "Ravi Takies",
        "Rokot",
        "Rudrapur",
        "Saheed Nagar",
        "sahid Nagar",
        "sailashree vihar",
        "Samantarapur",
        "Sameigadia",
        "Satyabhamapur",
        "Satyanagar",
        "Shahid nagar",
        "Sijua maujaa",
        "Sishupalgarh",
        "Sum Hospital",
        "Sundarpada",
        "Sundarpur",
        "Tamando",
        "Tankapani",
        "tankapani road",
        "Tomando",
        "Uttara Chack",
        "Vani Vihar",
        "vimatangi",
        "vss nagar"
    ],
    "Cuttack": [
        "Cuttack locality 1",
        "Cuttack locality 2"
    ],
    "Puri": [
        "Puri locality 1",
        "Puri locality 2"
    ]
}